# Generated by Django 3.0.3 on 2020-03-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
